name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Xocode 
      run: | 
        xcodebuild clean test -project Hiv2.xcodeproj \
        -scheme Hiv2 \
        -destination 'platform=iOS Simulator,name=iPhone 13 mini,OS=latest'
